version: '2'

networks:
  wakatime-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.7.0.0/16
          gateway: 172.7.238.1

volumes: 
  dbvolume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: wakatime-nginx
    ports:
      - "8201:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      wakatime-network:
        ipv4_address: 172.7.0.1

  mysql:
    image: mysql:5.7.29
    container_name: wakatime-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "8202:3306"
    volumes: 
      - dbvolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      wakatime-network:
        ipv4_address: 172.7.0.2

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wakatime-php
    volumes:
      - .:/var/www/html
    ports:
      - "8203:9000"
    networks:
      wakatime-network:
        ipv4_address: 172.7.0.3

# Insert into container wakatime-php
# docker exec -it wakatime-php sh